import { describe, expect, it } from 'vitest';
import { buildReleaseObjectKeys, publishRelease } from '../scripts/publish-r2.mjs';

describe('R2 publisher', () => {
  it('creates immutable versioned keys', () => expect(buildReleaseObjectKeys({ version: '0.1.3', commitSha: 'a'.repeat(40) })).toEqual(expect.objectContaining({ bundle: `releases/0.1.3/lastro-v2-${'a'.repeat(40)}.swbn` })));
  it('uploads release objects before updates.json and retains three versions', async () => {
    const calls: string[] = []; const store = new Map<string, Uint8Array>();
    const client = { send: async (command: { input: { Key: string; Body?: Uint8Array | string }; constructor: { name: string } }) => { const input = command.input; const key = input.Key as string; calls.push(key); if (command.constructor.name === 'GetObjectCommand') { if (!store.has(key)) throw Object.assign(new Error('missing'), { name: 'NotFound' }); const bytes = store.get(key) ?? new Uint8Array(); return { Body: { transformToByteArray: async () => bytes } }; } else if (command.constructor.name === 'PutObjectCommand') { const body = input.Body; const bytes = body instanceof Uint8Array ? body : new TextEncoder().encode(body); const old = store.get(key); if (old && Buffer.from(old).compare(Buffer.from(bytes)) !== 0) throw new Error('immutable conflict'); store.set(key, bytes); } else if (command.constructor.name === 'HeadObjectCommand') { if (!store.has(key)) throw Object.assign(new Error('missing'), { name: 'NotFound' }); return { ContentLength: store.get(key)?.byteLength ?? 0 }; } else if (command.constructor.name === 'DeleteObjectCommand') store.delete(key); else if (command.constructor.name === 'ListObjectsV2Command') return { Contents: [...store.keys()].filter(k => k.startsWith('releases/')).map(Key => ({ Key })) }; return {}; } };
    const result = await publishRelease({ client, bucket: 'bucket', artifacts: { bundle: new Uint8Array([1]), checksum: new Uint8Array([2]), releaseManifest: new Uint8Array([3]), auditReport: new Uint8Array([4]) }, metadata: { version: '0.1.3', commitSha: 'a'.repeat(40), bundleUrl: 'https://cdn.test/releases/0.1.3/app.swbn', updateManifestUrl: 'https://cdn.test/updates.json', channel: 'default', previousEntries: [{ version: '0.1.1', src: 'https://cdn.test/releases/0.1.1/app.swbn', channels: ['default'] }, { version: '0.1.2', src: 'https://cdn.test/releases/0.1.2/app.swbn', channels: ['default'] }] }, existingVersions: ['0.1.1', '0.1.2'], retentionCount: 3 });
    expect(result.version).toBe('0.1.3'); expect(calls.at(-1) ?? '').toBe('updates.json');
    const updates = JSON.parse(Buffer.from(store.get('updates.json') ?? []).toString());
    expect(updates.versions.map((entry: { version: string }) => entry.version)).toEqual(['0.1.3', '0.1.2', '0.1.1']);
  });
  it('overwrites the stable updates.json while keeping versioned objects immutable', async () => {
    const store = new Map<string, Uint8Array>([['updates.json', new TextEncoder().encode('{"versions":[]}')]]);
    const client = { send: async (command: { input: { Key: string; Body?: Uint8Array | string }; constructor: { name: string } }) => { const { Key: key } = command.input; if (command.constructor.name === 'GetObjectCommand') { if (!store.has(key)) throw Object.assign(new Error('missing'), { name: 'NotFound' }); const bytes = store.get(key) ?? new Uint8Array(); return { Body: { transformToByteArray: async () => bytes } }; } if (command.constructor.name === 'PutObjectCommand') { store.set(key, command.input.Body instanceof Uint8Array ? command.input.Body : new TextEncoder().encode(command.input.Body)); return {}; } if (command.constructor.name === 'ListObjectsV2Command') return { Contents: [] }; return {}; } };
    await publishRelease({ client, bucket: 'bucket', artifacts: { bundle: new Uint8Array([1]), checksum: new Uint8Array([2]), releaseManifest: new Uint8Array([3]), auditReport: new Uint8Array([4]) }, metadata: { version: '0.1.4', commitSha: 'b'.repeat(40), bundleUrl: 'https://cdn.test/releases/0.1.4/app.swbn', channel: 'default', previousEntries: [{ version: '0.1.3', src: 'https://cdn.test/old.swbn', channels: ['default'] }] }, existingVersions: ['0.1.3'], retentionCount: 3 });
    expect(JSON.parse(Buffer.from(store.get('updates.json') ?? []).toString()).versions[0].version).toBe('0.1.4');
  });
});
